### ISSUE TITLE
No adsabs-dev-api folder created when cloning the repo

### ISSUE THREAD

**Issue by Gabriel-p** [ryanvarley/adsbibtex#5]
The instructions in the `README.md` file says:

```
git clone https://github.com/ryanvarley/adsbibtex.git
cd adsabs-dev-api
python setup.py install
```

the command `cd adsabs-dev-api` does not work. The actual folder seems to be `adsbibtex`.

**Comment by ryanvarley** [comment]
yeah thats weird. Thanks, i'll change the readme.
