### ISSUE TITLE
Need sudo to install via python setup.py install?

### ISSUE THREAD

**Issue by Gabriel-p** [ryanvarley/adsbibtex#6]
After cloning the repo I tried `python setup.py install` and it failed with:

```
    [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/test-easy-install-14920.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python2.7/dist-packages/
```

I needed sudo privileges to access  the `/usr/local/*` folder.

**Comment by ryanvarley** [comment]
This is to do with your local python setup. Using anaconda or enthought python shouldn't have this issue, and isn't something the package can change.
