### ISSUE TITLE
AttributeError: 'Article' object has no attribute 'bibcode'

### ISSUE THREAD

**Issue by ryanvarley** [ryanvarley/adsbibtex#9]
When using the example config

**Comment by ryanvarley** [comment]
@Gabriel-p i will try to reproduce this tonight. I take it you haven't been able to get it to work at all because of this?

**Comment by Gabriel-p** [comment]
Yes.

**Comment by ryanvarley** [comment]
So this is weird, it just started happening to me. It seems to stem from either the ads api or the ads package i am using, i am raising an issue over there.
